# Configure automatic pull from upstream using config from https://github.com/wei/pull/issues/76
version: "1"
rules:
  - base: master
    upstream: bazelbuild:master
    autoMerge: true
    autoMergeHardReset: false
