# Configure automatic pull and merge from upstream, notifying CS to resolve conflicts
version: "1"
rules:
  - base: master
    upstream: bazelbuild:master
    mergeMethod: merge
    conflictReviewers:
      - cpsauer
